import "./globals.css"

import type { Metadata } from "next"
import { Geist, Geist_Mono, Roboto } from "next/font/google"

import { ThemeProvider } from "@/components/theme-provider"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin", "cyrillic"],
    weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html
            suppressHydrationWarning
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col font-sans">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}
